CREATE TABLE IF NOT EXISTS stories (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  text TEXT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_stories_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

ALTER TABLE characters
  ADD COLUMN story_id BIGINT UNSIGNED NULL,
  ADD CONSTRAINT fk_characters_story FOREIGN KEY (story_id) REFERENCES stories (id) ON DELETE CASCADE;

ALTER TABLE locations
  ADD COLUMN story_id BIGINT UNSIGNED NULL,
  ADD CONSTRAINT fk_locations_story FOREIGN KEY (story_id) REFERENCES stories (id) ON DELETE CASCADE;

ALTER TABLE scenes
  ADD COLUMN story_id BIGINT UNSIGNED NULL,
  ADD CONSTRAINT fk_scenes_story FOREIGN KEY (story_id) REFERENCES stories (id) ON DELETE CASCADE;
