CREATE TABLE IF NOT EXISTS conflicts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  text TEXT NULL,
  scene_id BIGINT UNSIGNED NULL,
  story_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_conflicts_scene FOREIGN KEY (scene_id) REFERENCES scenes (id) ON DELETE CASCADE,
  CONSTRAINT fk_conflicts_story FOREIGN KEY (story_id) REFERENCES stories (id) ON DELETE CASCADE
);
