package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code
// will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"strconv"

	"story-go-mysql/internal/graph/gqlmodel"
	"story-go-mysql/internal/model"
)

// CreateCharacter is the resolver for the createCharacter field.
func (r *mutationResolver) CreateCharacter(ctx context.Context, input gqlmodel.CharacterInput) (*gqlmodel.Character, error) {
	created, err := r.CharacterSvc.Create(ctx, model.CharacterRequest{Title: input.Title, Text: input.Text})
	if err != nil {
		return nil, err
	}
	return toGQLCharacter(created), nil
}

// Characters is the resolver for the characters field.
func (r *queryResolver) Characters(ctx context.Context) ([]*gqlmodel.Character, error) {
	page, err := r.CharacterSvc.List(ctx, model.ListParams{Page: 1, PageSize: model.MaxPageSize})
	if err != nil {
		return nil, err
	}
	out := make([]*gqlmodel.Character, len(page.Items))
	for i, c := range page.Items {
		out[i] = toGQLCharacter(c)
	}
	return out, nil
}

// Character is the resolver for the character field.
func (r *queryResolver) Character(ctx context.Context, id string) (*gqlmodel.Character, error) {
	parsed, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, err
	}
	c, err := r.CharacterSvc.Get(ctx, parsed)
	if err != nil {
		return nil, err
	}
	return toGQLCharacter(c), nil
}

// Scenes is the resolver for the scenes field.
func (r *queryResolver) Scenes(ctx context.Context) ([]*gqlmodel.Scene, error) {
	page, err := r.SceneSvc.List(ctx, model.ListParams{Page: 1, PageSize: model.MaxPageSize})
	if err != nil {
		return nil, err
	}
	out := make([]*gqlmodel.Scene, len(page.Items))
	for i, s := range page.Items {
		out[i] = toGQLScene(s)
	}
	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// --- Mapeo de los modelos del dominio a los modelos de GraphQL ---

func toGQLCharacter(c model.Character) *gqlmodel.Character {
	return &gqlmodel.Character{ID: strconv.FormatUint(c.ID, 10), Title: c.Title, Text: c.Text}
}

func toGQLLocation(l model.Location) *gqlmodel.Location {
	return &gqlmodel.Location{ID: strconv.FormatUint(l.ID, 10), Title: l.Title, Text: l.Text}
}

func toGQLScene(s model.Scene) *gqlmodel.Scene {
	characters := make([]*gqlmodel.Character, len(s.Characters))
	for i, c := range s.Characters {
		characters[i] = toGQLCharacter(c)
	}
	locations := make([]*gqlmodel.Location, len(s.Locations))
	for i, l := range s.Locations {
		locations[i] = toGQLLocation(l)
	}
	return &gqlmodel.Scene{
		ID:            strconv.FormatUint(s.ID, 10),
		Title:         s.Title,
		Text:          s.Text,
		StartTimeline: s.StartTimeline,
		EndTimeline:   s.EndTimeline,
		Characters:    characters,
		Locations:     locations,
	}
}
