// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

type Character struct {
	ID    string  `json:"id"`
	Title string  `json:"title"`
	Text  *string `json:"text,omitempty"`
}

type CharacterInput struct {
	Title string  `json:"title"`
	Text  *string `json:"text,omitempty"`
}

type Location struct {
	ID    string  `json:"id"`
	Title string  `json:"title"`
	Text  *string `json:"text,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Scene struct {
	ID            string       `json:"id"`
	Title         string       `json:"title"`
	Text          *string      `json:"text,omitempty"`
	StartTimeline int          `json:"startTimeline"`
	EndTimeline   int          `json:"endTimeline"`
	Characters    []*Character `json:"characters"`
	Locations     []*Location  `json:"locations"`
}
